[package]
name = "secop-derive"
version = "0.1.1"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
synstructure = "0.12"
darling = "0.10"
