[package]
name = "secop-derive"
version = "0.1.1"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"
synstructure = "0.10"
darling = "0.8"
