[package]
name = "secop-derive"
version = "0.1.1"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.5"
quote = "1.0.2"
syn = "1.0.5"
synstructure = "0.12.1"
darling = "0.12.2"
